/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnl_main.java
 *
 * Created on 11 30, 12, 2:23:25 PM
 */
package saving_to_usb;

import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import mijzcx.synapse.desk.utils.*;

import saving_to_usb.to.to_data;
import saving_to_usb.utl.get_from_usb;
import saving_to_usb.utl.save_to_usb;

/**
 *
 * @author mijzcx
 */
public class pnl_main extends javax.swing.JPanel {

    /**
     * Creates new form pnl_main
     */
    public pnl_main() {
        initComponents();
        myInit();
    }

    //<editor-fold defaultstate="collapsed" desc="main">
    public static void main(String[] args) {
        Application.setSystemLookAndFeel();
        pnl_main pnl = new pnl_main();
        Application.launchMainFrame(pnl, "pnl_main2");

    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_clear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tf_i_data = new javax.swing.JTextField();
        tf_b_data = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_d_data = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_dt_data = new javax.swing.JTextField();
        tf_s_data = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_open = new javax.swing.JButton();

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Integer Data");

        jLabel7.setText("Double Data");

        jLabel8.setText("Date Data");

        jLabel9.setText("Boolean Data");

        jLabel10.setText("String Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(tf_s_data, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_i_data, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_dt_data, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(tf_d_data)
                            .addComponent(tf_b_data))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_s_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_i_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_d_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_dt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_b_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_open.setText("Open");
        btn_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_open, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_open))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btn_clear)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        save();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openActionPerformed
        open();
    }//GEN-LAST:event_btn_openActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_open;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_b_data;
    private javax.swing.JTextField tf_d_data;
    private javax.swing.JTextField tf_dt_data;
    private javax.swing.JTextField tf_i_data;
    private javax.swing.JTextField tf_s_data;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
    }

    private void open() {

        String path = System.getProperty("user.home");
        JFileChooser f = new JFileChooser(path + "/");

        f.setDialogTitle("Open To Ending Inventory");
        f.setFileFilter(new FileNameExtensionFilter("Test", "secret"));
        f.setAcceptAllFileFilterUsed(false);
        f.setControlButtonsAreShown(true);
        f.setMultiSelectionEnabled(false);
        int action = f.showDialog(this, "Open");
        if (action == JFileChooser.APPROVE_OPTION) {
            File file = f.getSelectedFile();
            if (file.getName().
                    isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please choose a filename");
            }

            try {

                to_data to = (to_data) get_from_usb.get(file);
                fill_to_data(to);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }
    }

    private void save() {

        String path = System.getProperty("user.home");
        JFileChooser f = new JFileChooser(path + "/");
        f.setDialogTitle("Save Ending Inventory");
        f.setMultiSelectionEnabled(false);
        f.setFileFilter(new FileNameExtensionFilter("Test", "secret"));
        f.setApproveButtonText("Save");
        f.setApproveButtonMnemonic('S');
        f.setAcceptAllFileFilterUsed(false);

        int action = f.showDialog(this, "Save");
        if (action == JFileChooser.APPROVE_OPTION) {
            File file = f.getSelectedFile();

            if (file.getName().
                    isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please choose a filename");
            }

            try {
                save_to_usb.save(file, get_to_data());

                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }

    }

    private to_data get_to_data() {
        String s_data = tf_s_data.getText();
        int i_data = FitIn.toInt(tf_i_data.getText());
        double d_data = FitIn.toDouble(tf_d_data.getText());
        Date dt_data = FitIn.to_date(tf_dt_data.getText(), DateUtil.FMT_Ascii_format);
        boolean b_data = FitIn.toBoolean(tf_b_data.getText());
        to_data to = new to_data(s_data, i_data, d_data, dt_data, b_data);

        Lg.$.severe(to.toString());
        return to;
    }

    private void clear() {
        To.clear(tf_b_data, tf_d_data, tf_dt_data, tf_i_data, tf_s_data);
    }

    private void fill_to_data(to_data to) {
        tf_s_data.setText(to.getS_data());
        tf_i_data.setText(FitIn.fmt_woc(to.getI_data()));
        tf_d_data.setText(FitIn.fmt_wc_0(to.getD_data()));
        tf_dt_data.setText(FitIn.fmt_date(to.getDt_data(), DateUtil.FMT_Ascii_format));
        tf_b_data.setText(Boolean.toString(to.isB_data()));
    }
}
